---
title: Improving channel selection in IEEE802.11 networks by scanning from access points
author: Nicolas Harlem Eide

abstract: Write the abstract!

preface: I would like to thank _Torleiv Maseng_, _Madeleine Victoria Kongshavn_,
  and _Magnus Skjegstad_ for all their help and supervision while writing this
  thesis. I would also like to thank _Julie Eldøy_ for always being there for me,
  and being an all around amazing girlfriend. Thanks to _Thor Høgås_ and
  _Karl Hole Totland_ for being my good friends and study-budies via video-chat
  almost every day while we wrote each of our theses. Last but not least, thanks
  to my parrents for helping me get to this point!

toc: yes
lof: yes
lot: yes

# Latex options
documentclass: ifimaster
classoption: UKenglish

header-includes: \usepackage{subcaption}

mainfont: XCharter

linkcolor: blue

bibliography: source/references.bib
csl: static/ieee.csl
---
